### ISSUE TITLE
Zoom Integration?

### ISSUE THREAD

**Issue by nab138** [Robloche/chartjs-plugin-streaming#4]
On the docs under integration and zoom plugin, it says:
> This plugin requires chartjs-plugin-zoom 1.x.

And Installing the current version of chartjs-plugin-zoom doesn't work (well, it does, but the custom limit properties do not work, which I need as the default zoom limits don't do anything with this plugin). v1.3.0 of the zoom plugin is deprecated but doesn't work either anyways, and v1.2.1 is not compatible with chart.js 4.x.

**Comment by Robloche** [comment]
I'm sorry but I'm not the maintainer of the original package. I just fork it for my own use.
Maybe you could do the same thing?

**Comment by nab138** [comment]
Thanks for the quick response, I'll see what I can do in a fork
