### ISSUE TITLE
The plugin needs to check if value that me.getDatasetMeta(datasetIndex) is valid

### ISSUE THREAD

**Issue by morimoriysmoon** [Robloche/chartjs-plugin-streaming#6]
Hi!
I am using this plugin with vuejs (and vuetify) project and so happy with it.

However I am running into an issue when I deactivate a component using chartjs and activate it again.
It means that the component is still alive but is detached from DOM!

I tried to disable the plugin (locally or globally) but no good.

According to my research, chartjs stops animating and **removes all metasets** when its canvas is detached from DOM. (https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js#L1020)
As a result, me.getDatasetMeta(datasetIndex) returns meta data filled with null.
So controller._setStyle = function(...) {} throws exception.

![image](https://github.com/Robloche/chartjs-plugin-streaming/assets/1762090/14d301bc-3587-4fcb-990a-87e8654ba64c)

I think it can be workaround for my issue to check if canvas of chartjs is attached to DOM.
![image](https://github.com/Robloche/chartjs-plugin-streaming/assets/1762090/fe13d8ed-9625-42a8-ac09-5646a001c676)

Thanks for your time!

**Comment by Robloche** [comment]
Sorry but I don't have time right now to work on this.
Fix it yourself and open a PR.
Or fork it, if you prefer...

**Comment by Robloche** [comment]
Fixed by https://github.com/Robloche/chartjs-plugin-streaming/pull/7.

**Comment by Jimmy-sheep** [comment]
@Robloche Sorry for bothering you, will you publish this PR to npm?

**Comment by Robloche** [comment]
> @Robloche Sorry for bothering you, will you publish this PR to npm?

I'm just back from vacations. Hence, a lot of things to catch up. I'll try to release it but I can't promise it'll be fast.
